name: wf-ci-production

on:
  pull_request:
    branches:
      - "production"

jobs:
  ci-production-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # Fixing issues

      - name: Lint CSS
        run: |
          npx stylelint "**/*.css"
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Lint PHP Files
        run: ~/.composer/vendor/bin/phpcs --standard=PSR12 **/*.php

      # - name: Test Build in Production
      #   run: |
      #     npx parcel build ".index.php" --dist-dir "./dist" --public-url "./"
